### ISSUE TITLE
Assertion triggers due to floating point precision

### ISSUE THREAD

**Issue by moepmoep12** [m4saka/xxr#13]
https://github.com/m4saka/xxr/blob/a58ab608ac57e3402d3b164e06da6cef653a4290/include/xxr/xcs/action_set.hpp#L142

For timestamps > 10000 the assertion evaluates to false due to a deviation in the ~12th digit.
For example,  averageTimeStamp = 20833.000000000004 != 20833.

I assume this is not intended.

- XCSR::CSR
- MSVC Compiler
- Commit a58ab608ac57e3402d3b164e06da6cef653a4290

**Comment by m4saka** [comment]
Sorry, actually I faced the same problem and fixed in the commit 8f2118f1675cf7807328687df7ca81b17648420c in a newer branch `exp_interface`, but that was not merged to the master branch yet.

I have fixed this issue in the master branch.
Thank you for the report.

Commit 3eabee3 :
```diff
-           assert(averageTimeStamp <= timeStamp);
+           assert(averageTimeStamp < timeStamp + 1);
```
